title: Causal Educational Tool
description: |
  <p>Trying out the GitHub test page for the causal educational tool</p>
baseurl: ""
url: "https://causal-educational-tool.github.io"

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
